### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by johalun** [M680x0/M680x0-mono-repo#11]
What is the status of this project? Would be nice with a wiki page or readme about the specific m68k parts. Thanks!

**Comment by mshockwave** [comment]
Hi! on the technical side we are almost ready. We will kick off the upstream discussion on LLVM mailing in few days.

**Comment by johalun** [comment]
That's awesome! Thanks for the update!

**Comment by glaubitz** [comment]
@johalun We're planning to have a discussion on the project during the next m68k online meeting, see: http://m68k.info/

**Comment by johalun** [comment]
Great, I'll definitely join on Friday. 

Do you have any examples on how to build your LLVM branch for cross compiling from x86_64 Linux to m68k? I'm very interested in cross compiling Rust to Amiga m68k :)

**Comment by glaubitz** [comment]
Just build LLVM as you would normally do:

```bash
$ mkdir build
$ cd build
$ cmake ../llvm -DLLVM_TARGETS_TO_BUILD="X86;M680x0" -DLLVM_ENABLE_PROJECTS=clang
$ make
```

then use ```clang``` as shown below:

> https://lists.debian.org/debian-68k/2020/06/msg00030.html

For the m68k backend for Rust, see: https://github.com/glaubitz/rust/tree/m68k-linux

**Comment by johalun** [comment]
Exciting!! What's the status of the Rust patches? I'm having trouble building the Rust repo.

**Comment by glaubitz** [comment]
They need to be rebased with the latest Rust upstream tree. Then there might be a chance to get them to build.

**Comment by johalun** [comment]
Hmm, keep getting build error on this repo. It is irrelevant of m68k backend so might be my setup.. Ubuntu 20.04.
```
/home/johalun/dev/M680x0-mono-repo/clang/lib/Sema/SemaDeclAttr.cpp:5814:45: error: cannot convert ‘llvm::APSInt’ to ‘const clang::ASTContext&’
 5814 |   if (!NumParamsExpr->isIntegerConstantExpr(NumParams, S.Context)) {
      |                                             ^~~~~~~~~
      |                                             |
      |                                             llvm::APSInt
In file included from /home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/DeclCXX.h:22,
                 from /home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/CXXInheritance.h:17,
                 from /home/johalun/dev/M680x0-mono-repo/clang/lib/Sema/SemaDeclAttr.cpp:16:
/home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/Expr.h:533:48: note:   initializing argument 1 of ‘bool clang::Expr::isIntegerConstantExpr(const clang::ASTContext&, clang::SourceLocation*) const’
  533 |   bool isIntegerConstantExpr(const ASTContext &Ctx,
      |                              ~~~~~~~~~~~~~~~~~~^~~
```

**Comment by johalun** [comment]
Oh wait, that file was actually touched in a recent commit d500bad0e3a252e97973a152aa30d57dc3deb30d

**Comment by mshockwave** [comment]
> Hmm, keep getting build error on this repo. It is irrelevant of m68k backend so might be my setup.. Ubuntu 20.04.
> 
> ```
> /home/johalun/dev/M680x0-mono-repo/clang/lib/Sema/SemaDeclAttr.cpp:5814:45: error: cannot convert ‘llvm::APSInt’ to ‘const clang::ASTContext&’
>  5814 |   if (!NumParamsExpr->isIntegerConstantExpr(NumParams, S.Context)) {
>       |                                             ^~~~~~~~~
>       |                                             |
>       |                                             llvm::APSInt
> In file included from /home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/DeclCXX.h:22,
>                  from /home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/CXXInheritance.h:17,
>                  from /home/johalun/dev/M680x0-mono-repo/clang/lib/Sema/SemaDeclAttr.cpp:16:
> /home/johalun/dev/M680x0-mono-repo/clang/include/clang/AST/Expr.h:533:48: note:   initializing argument 1 of ‘bool clang::Expr::isIntegerConstantExpr(const clang::ASTContext&, clang::SourceLocation*) const’
>   533 |   bool isIntegerConstantExpr(const ASTContext &Ctx,
>       |                              ~~~~~~~~~~~~~~~~~~^~~
> ```

This error was caused by recent rebasing onto upstream. I just fixed that.

Also, in preparation for the upstreaming process, now `M680x0` is an experimental target, so please use the following cmake command instead:
```
cmake -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="M680x0" -DLLVM_TARGETS_TO_BUILD="X86" <reset of the cmake arguments> ../llvm
```
