### ISSUE TITLE
Fail to build compiler and produce m68k binary...

### ISSUE THREAD

**Issue by johalun** [M680x0/M680x0-mono-repo#12]
This gist contain most info 

https://gist.github.com/johalun/a0c1886dfdec9256e5063c1bb9bc9227

I'm trying to reproduce https://lists.debian.org/debian-68k/2020/06/msg00030.html but getting weird errors.
Building clang always fails but simply re-run ninja / make a couple of times and it succeeds. 
When then trying to cross compile the c program, it tries to use /usr/bin/as which fails.

Am I missing something here?

**Comment by glaubitz** [comment]
Looks like you don't have a proper Multi-Arch environment with the proper toolchain and library support for m68k. I recommend using Debian unstable and installing libraries through Debian Ports.

See for example: https://wiki.debian.org/PortsDocs/BootstrappingOpenJDK (adopt to your usecase)

**Comment by mshockwave** [comment]
Though i haven't looked into it, I wondered why it was using GNU AS rather than LLVM's builtin assembler...maybe you can try to use `m680x0-unknown-linux` as the triple?

**Comment by johalun** [comment]
I installed `gcc-m68k-linux-gnu` and then it works! However, it's not using the llvm tools regardless of target triple:

```
johalun@xc8 /o/llvm-m68k> ./bin/clang -target m68k-unknown-linux-gnu /tmp/hello.c -o /tmp/hello.m68k -v
clang version 12.0.0 (git@github.com:M680x0/M680x0-mono-repo.git c5834ffbda019df8c94c669c658d804cb9c19af3)
Target: m68k-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm-m68k/./bin
Found candidate GCC installation: /usr/lib/gcc-cross/m68k-linux-gnu/9
Selected GCC installation: /usr/lib/gcc-cross/m68k-linux-gnu/9
Candidate multilib: .;@m32
Selected multilib: .;@m32
 "/opt/llvm-m68k/bin/clang-12" -cc1 -triple m68k-unknown-linux-gnu -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -no-integrated-as -mconstructor-aliases -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /opt/llvm-m68k/lib/clang/12.0.0 -internal-isystem /usr/local/include -internal-isystem /opt/llvm-m68k/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fno-dwarf-directory-asm -fdebug-compilation-dir /opt/llvm-m68k -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -o /tmp/hello-d86afe.s -x c /tmp/hello.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /opt/llvm-m68k/lib/clang/12.0.0/include
 /usr/include
End of search list.
 "/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/bin/as" -o /tmp/hello-a726de.o /tmp/hello-d86afe.s
 "/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m m68kelf -dynamic-linker /lib/ld.so.1 -o /tmp/hello.m68k /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crt1.o /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crti.o /usr/lib/gcc-cross/m68k-linux-gnu/9/crtbegin.o -L/usr/lib/gcc-cross/m68k-linux-gnu/9 -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../m68k-linux-gnu -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../lib -L/opt/llvm-m68k/bin/../lib -L/lib/m68k-linux-gnu -L/lib/../lib -L/usr/lib/m68k-linux-gnu -L/usr/lib/../lib -L/usr/lib/m68k-linux-gnu/../../lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../.. -L/opt/llvm-m68k/bin/../lib -L/lib -L/usr/lib /tmp/hello-a726de.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc-cross/m68k-linux-gnu/9/crtend.o /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crtn.o

```

**Comment by mshockwave** [comment]
> johalun@xc8 /o/llvm-m68k> ./bin/clang -target m68k-unknown-linux-gnu /tmp/hello.c -o /tmp/hello.m68k -v

have you tried to remove the `gnu` from the triple as I suggested earlier?

**Comment by johalun** [comment]
Yes, any variant of m68k/m680x0-unknown-linux (-gnu) yields the same result.

**Comment by glaubitz** [comment]
@johalun Definitely looks like a problem with your build environment. I just checked out the latest source tree and was able to build m68k binaries without any problems.

```
glaubitz@epyc:..M680x0-mono-repo/build> cat hello.c 
#include <stdio.h>

int main() {
        printf("Hello World!\n");
        return 0;
}

glaubitz@epyc:..M680x0-mono-repo/build> ./bin/clang -target m68k-linux-gnu ~/hello.c -o hello.m68k
glaubitz@epyc:..M680x0-mono-repo/build> file hello.m68k 
hello.m68k: ELF 32-bit MSB executable, Motorola m68k, 68020, version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 3.2.0, not stripped
glaubitz@epyc:..M680x0-mono-repo/build>
```

I can recommend to use Debian unstable for these experiments with the Debian Ports repositories enabled.

**Comment by johalun** [comment]
@glaubitz What's your output if you add `-v`?

**Comment by johalun** [comment]
Looking llvm-config output it seems m68k is missing asmparser. Is that expected?

johalun@xc8 /o/llvm-m68k> ./bin/llvm-config --components
aggressiveinstcombine all all-targets analysis asmparser asmprinter binaryformat bitreader bitstreamreader bitwriter cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions frontendopenmp fuzzmutate globalisel instcombine instrumentation interfacestub interpreter ipo irreader jitlink libdriver lineeditor linker lto m680x0 m680x0codegen m680x0desc m680x0info mc mca mcdisassembler mcjit mcparser mirparser native nativecodegen objcarcopts object objectyaml option orcerror orcjit passes profiledata remarks runtimedyld scalaropts selectiondag support symbolize tablegen target textapi transformutils vectorize windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xray

**Comment by glaubitz** [comment]
@johalun What kind of environment are you using? From your error message, it's very obvious that LLVM is using the wrong assembler on your machine. It's using the native assembler of the host system instead of ```m68k-linux-gnu-as```:

```bash
 "/usr/bin/as" -o /tmp/hello-26b5ea.o /tmp/hello-accfd2.s
/tmp/hello-accfd2.s: Assembler messages:
/tmp/hello-accfd2.s:7: Error: no such instruction: `move.l %a6,-(%sp)'
/tmp/hello-accfd2.s:8: Error: no such instruction: `move.l %sp,%a6'
/tmp/hello-accfd2.s:9: Error: no such instruction: `sub.l '
/tmp/hello-accfd2.s:10: Error: no such instruction: `move.l '
/tmp/hello-accfd2.s:11: Error: no such instruction: `move.l '
/tmp/hello-accfd2.s:12: Error: no such instruction: `add.l '
/tmp/hello-accfd2.s:13: Error: no such instruction: `move.l (%sp)+,%a6'
/tmp/hello-accfd2.s:14: Error: no such instruction: `rts'
```

It's invoking ```/usr/bin/as```. It should be invoking ```/usr/bin/m68k-linux-gnu-as```. This definitely works here and I don't think it's an issue with the LLVM code.

**Comment by johalun** [comment]
I'm on ubuntu 20.04. If I install the gcc-m68k-linux-gnu ubuntu package, then it is using the gnu as for asm and produces the correct binary. I thought this was not correct as per @mshockwave 's comment and it was supposed to use llvm-as. 

```
johalun@xc8 ~/d/M/build (master) [1]> ./bin/clang -target m68k-unknown-linux /tmp/hello.c -o /tmp/hello.m68k -v
clang version 12.0.0 (git@github.com:M680x0/M680x0-mono-repo.git c5834ffbda019df8c94c669c658d804cb9c19af3)
Target: m68k-unknown-linux
Thread model: posix
InstalledDir: /home/johalun/dev/M680x0-mono-repo/build/./bin
Found candidate GCC installation: /usr/lib/gcc-cross/m68k-linux-gnu/9
Selected GCC installation: /usr/lib/gcc-cross/m68k-linux-gnu/9
Candidate multilib: .;@m32
Selected multilib: .;@m32
 "/home/johalun/dev/M680x0-mono-repo/build/bin/clang-12" -cc1 -triple m68k-unknown-linux -S -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -fno-verbose-asm -no-integrated-as -mconstructor-aliases -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /home/johalun/dev/M680x0-mono-repo/build/lib/clang/12.0.0 -internal-isystem /usr/local/include -internal-isystem /home/johalun/dev/M680x0-mono-repo/build/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fno-dwarf-directory-asm -fdebug-compilation-dir /home/johalun/dev/M680x0-mono-repo/build -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -o /tmp/hello-fb5bfe.s -x c /tmp/hello.c
clang -cc1 version 12.0.0 based upon LLVM 12.0.0git default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /home/johalun/dev/M680x0-mono-repo/build/lib/clang/12.0.0/include
 /usr/include
End of search list.
 "/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/bin/as" -o /tmp/hello-110f71.o /tmp/hello-fb5bfe.s
 "/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/bin/ld" -z relro --hash-style=gnu --eh-frame-hdr -m m68kelf -dynamic-linker /lib/ld.so.1 -o /tmp/hello.m68k /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crt1.o /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crti.o /usr/lib/gcc-cross/m68k-linux-gnu/9/crtbegin.o -L/usr/lib/gcc-cross/m68k-linux-gnu/9 -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../m68k-linux-gnu -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../lib -L/home/johalun/dev/M680x0-mono-repo/build/bin/../lib -L/lib/m68k-linux-gnu -L/lib/../lib -L/usr/lib/m68k-linux-gnu -L/usr/lib/../lib -L/usr/lib/m68k-linux-gnu/../../lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib -L/usr/lib/gcc-cross/m68k-linux-gnu/9/../../.. -L/home/johalun/dev/M680x0-mono-repo/build/bin/../lib -L/lib -L/usr/lib /tmp/hello-110f71.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc-cross/m68k-linux-gnu/9/crtend.o /usr/lib/gcc-cross/m68k-linux-gnu/9/../../../../m68k-linux-gnu/lib/../lib/crtn.o
johalun@xc8 ~/d/M/build (master)> file /tmp/hello.m68k 
/tmp/hello.m68k: ELF 32-bit MSB executable, Motorola m68k, 68020, version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 3.2.0, not stripped

```

**Comment by glaubitz** [comment]
There is no LLVM assembler for m68k yet.

**Comment by johalun** [comment]
That explains it :) I guess that's not a priority for now, especially since as long as we can produce m68k assembly there are tools out there to cross compile for various m68k platforms, and of course natively as well.

I did another build of llvm over night but this time with `-j2` instead of `-j12` and it passed one go without failure so I guess it's not really robust against many parallel build processes. Ninja had the same problem. 

That's answers everything in this issue so I'll go ahead and close it.

**Comment by glaubitz** [comment]
> That explains it :) I guess that's not a priority for now, especially since as long as we can produce m68k assembly there are tools out there to cross compile for various m68k platforms, and of course natively as well.

Well, there aren't even LLVM asssemblers for all the other architectures that LLVM supports. Likewise LLDB and the other support libraries.

> I did another build of llvm over night but this time with -j2 instead of -j12 and it passed one go without failure so I guess it's not really robust against many parallel build processes. Ninja had the same problem.

I can't reproduce that problem either. I'm building with an AMD EPYC with 64 cores with Ninja and cmake and the builds are 100% reliable.

**Comment by glaubitz** [comment]
> There is no LLVM assembler for m68k yet.

After yesterday's talk, I stand corrected. Apparently, being able to use the internal assembler is already supposed to be possible.

**Comment by mshockwave** [comment]
I know this issue was closed, but with the latest changes (in the master branch), it will use the integrated assembler by default now

**Comment by johalun** [comment]
I'm getting one step further now but fails at trying to link with /usr/bin/ld which doesn't support m68k-elf.

**Comment by glaubitz** [comment]
@johalun Do you have a cross binutils for m68k installed? You need proper Multi-Arch support for this to work.

**Comment by johalun** [comment]
You mean the gcc stuff? No, I uninstalled them thinking that only the llvm toolchain would be enough (built both with "clang;lld")

**Comment by glaubitz** [comment]
There is no LLDB for m68k yet, so you need to have a cross-linker installed.

**Comment by johalun** [comment]
Ah, I see. Jumping the gun again :) Thanks for clarifying.

**Comment by johalun** [comment]
I will try to install only binutils-m68k-linux-gnu and not the gcc-m68k stuff and see how that goes.

**Comment by mshockwave** [comment]
Linker support (i.e. LLD) is on our TODO list, eventually we hope the entire toolchain (compiler, assembler, linker, C++/C libraries, compiler runtime) to be LLVM
