### ISSUE TITLE
Missing definition of getExceptionPointerRegister and getExceptionSelectorRegister

### ISSUE THREAD

**Issue by glaubitz** [M680x0/M680x0-mono-repo#15]
We need to define ```getExceptionPointerRegister``` and ```getExceptionSelectorRegister``` in ```M680x0ISelLowering.cpp``` which are required for exception handling. They are also required by the Rust compiler.

I think the relevant gcc code might be here: https://github.com/gcc-mirror/gcc/blob/master/gcc/config/m68k/m68k.h#L741

**Comment by glaubitz** [comment]
According to this discussion [1] on the GCC mailing list, the corresponding registers on m68k are ```d0``` and ```d1```.

Not sure though how these are referenced within LLVM context, is it ```M680x0::D0``` and ```M680x0::D1```? I don't see an explicit definition of ```D0``` and ```D1``` in ```M680x0RegisterInfo.td```, but the register names are referenced.

> [1] https://gcc.gnu.org/pipermail/gcc/2020-October/233872.html

**Comment by glaubitz** [comment]
Could be that we are generally missing the definition of ```DwarfRegNum``` similar to [1].

> [1] https://github.com/M680x0/M680x0-mono-repo/blob/master/llvm/lib/Target/Sparc/SparcRegisterInfo.td#L126

**Comment by jrtc27** [comment]
I don't _think_ you need to define the DWARF register number for exception handling to work, but it's not an area I know a huge amount about. Though you should define them anyway if you want debugging to not be extremely frustrating :)

But, yes, it seems D0 and D1 are correct:
```
root@epyc:~> echo 'void foo() { try { throw 424242; } catch (int x) {} }' | m68k-linux-gnu-gcc -x c++ - -o - -S -O2
```
```asm
	# ...
.LEHB0:
	.cfi_escape 0x2e,0xc
	jsr __cxa_throw
.LEHE0:
.L4:
	.cfi_restore_state
	subq.l #1,%d1		# Check whether the selector is 1, ie that the object thrown corresponds to our first and only catch
	jeq .L3
	move.l %d0,-(%sp)	# Pass %d0, ie the exception object, to _Unwind_Resume
	.cfi_remember_state
	.cfi_def_cfa_offset 12
.LEHB1:
	jsr _Unwind_Resume
.LEHE1:
.L3:
	.cfi_restore_state
	move.l %d0,-(%sp)	# Pass %d0, ie the exception object, to __cxa_begin_catch
	.cfi_def_cfa_offset 12
	jsr __cxa_begin_catch
	addq.l #4,%sp
	.cfi_def_cfa_offset 8
	move.l (%sp)+,%d2
	jra __cxa_end_catch
	.cfi_endproc
	# ...
```

And here's where D0 and D1 are defined:
https://github.com/M680x0/M680x0-mono-repo/blob/4212979781f78faf1fc6ff5e93707d735809a398/llvm/lib/Target/M680x0/M680x0RegisterInfo.td#L41

**Comment by glaubitz** [comment]
Thanks. I the ```foreach``` definition made me miss it in the ```.td``` file. Guess it should be very easy to implement then.

**Comment by glaubitz** [comment]
I created #17 now.

**Comment by glaubitz** [comment]
> I don't think you need to define the DWARF register number for exception handling to work, but it's not an area I know a huge amount about.

It seems it's necessary for Rust.
