### ISSUE TITLE
Remove the workaround for gcc.90538?

### ISSUE THREAD

**Issue by Chandlerooo** [M680x0/M680x0-mono-repo#28]
I notice a workaround for gcc.90538 in AsmPrinter.cpp introduced by commit https://github.com/M680x0/M680x0-mono-repo/commit/6cd232056c3cdaf5e9eb85ede8e42d0db97f0f71: 
https://github.com/M680x0/M680x0-mono-repo/blob/7b55e63dbaf424c615a7802dc17b42b99681921b/mlir/lib/IR/AsmPrinter.cpp#L1763-L1785
This bug has been marked as fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90538. Shall it be removed?

**Comment by glaubitz** [comment]
This should be reported to LLVM upstream, see: https://github.com/llvm/llvm-project/issues

**Comment by Chandlerooo** [comment]
Thanks.
