### ISSUE TITLE
clang driver code needs to learn about different sub-architectures

### ISSUE THREAD

**Issue by glaubitz** [M680x0/M680x0-mono-repo#9]
Looking at ```clang/lib/Driver/ToolChains/Arch/PPC.cpp``` and comparing that with the M680x0 variant, we need to add code to select the correct sub-architecture depending on the sub-architecture type specified on the command line, e.g ```-m68020```.

**Comment by mshockwave** [comment]
As mentioned in the commit message. This only fixes part of the story in driver. Codegen part still hasn't supported sub-architectures.

**Comment by glaubitz** [comment]
Great, thank you!
